# Generated by Django 3.2.6 on 2021-09-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
    ]
