# Generated by Django 3.2.6 on 2021-09-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
        migrations.AddField(
            model_name='job',
            name='job_tyep',
            field=models.CharField(choices=[('full time', 'full time'), ('part time', 'part time')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
